# This is a basic workflow to help you get started with Actions

name: Build Clang Power Tools and generate vsix with Advenced Installer

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        
      - name: Restore dependencies
        run: dotnet restore ClangPowerTools\ClangPowerTools.sln

      - name: Build app for release
        run: msbuild ${{ github.workspace }}\ClangPowerTools\ClangPowerTools.sln -t:rebuild -property:Configuration=Release

  generate-aip:
    runs-on: windows-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        
      - name: Restore dependencies
        run: dotnet restore ClangPowerTools\ClangPowerTools.sln

      - name: Build app for release
        run: msbuild ${{ github.workspace }}\ClangPowerTools\ClangPowerTools.sln -t:rebuild -property:Configuration=Release
      - name: Create ClangPowerTools.vsix- build AIP
        uses: caphyon/advinst-github-action@v1.0
        with:
          advinst-license: ${{ secrets.ADVINST_LICENSE_KEY }}
          advinst-enable-automation: 'true'
          aip-path: ${{ github.workspace }}\ClangPowerTools\ClangPowerTools.aip
      - run: |
          AdvancedInstaller.com /edit ${{ github.workspace }}\ClangPowerTools\ClangPowerTools.aip /SetProperty Identifier="Caphyon.9ce239f2-d27a-432c-906c-1d55a123dbfd"
          AdvancedInstaller.com /edit ${{ github.workspace }}\ClangPowerTools\ClangPowerTools.aip /SetProperty Name="Clang Power Tools 2022"
          AdvancedInstaller.com /edit ${{ github.workspace }}\ClangPowerTools\ClangPowerTools.aip /SetPackageName ClangPowerTools2022

      - name: Create ClangPowerTools2022.vsix - build AIP
        uses: caphyon/advinst-github-action@v1.0
        with:
          advinst-license: ${{ secrets.ADVINST_LICENSE_KEY }}
          advinst-enable-automation: 'true'
          aip-path: ${{ github.workspace }}\ClangPowerTools\ClangPowerTools.aip

     
      - name: Archive production ClangPowerTools artifacts (cpt generated with advanced installer)
        uses: actions/upload-artifact@v4
        with:
          name: VsixAI
          path: ${{ github.workspace }}\ClangPowerTools\VsixAI\ClangPowerTools.vsix

      - name: Archive production ClangPowerTools 2022 artifacts (cpt 2022 generated with advanced installer)
        uses: actions/upload-artifact@v4
        with:
          name: VsixAI2022
          path: ${{ github.workspace }}\ClangPowerTools\VsixAI\ClangPowerTools2022.vsix
      


